def fONOFFSelect(No):
    switch = {0 : '0_OFF', 
              1 : '1_ON',
              }

    return switch.get(No, '0_OFF')
    
def fZRTModeSelect(No):
    switch = {0 : '0_DIR', 
              1 : '1_INDIR',
              2 : '2_IMMED',
              }

    return switch.get(No, '0_DIR')

def fSpeedModeSelect(No):
    switch = {0 : '0_UltraSPD', 
              1 : '1_AVDSPD',
              2 : '2_SelfSPD',
              }

    return switch.get(No, '0_UltraSPD')

def fZRTSignalSelect(No):
    switch = {0 : '0_Low', 
              1 : '1_High',
              2 : '2_NoRef',
              }

    return switch.get(No, '0_Low')

def fCoreCalibrateSelect(No):
    switch = {0 : '0_DEFAULT', 
              1 : '1_USER',
              }

    return switch.get(No, '0_DEFAULT')

def fXEncoderSelect(No):
    switch = {0 : '0_DEFAULT', 
              1 : '1_4000',
              }

    return switch.get(No, '0_DEFAULT')

def fYEncoderSelect(No):
    switch = {0 : '0_DEFAULT', 
              1 : '1_4000',
              }

    return switch.get(No, '0_DEFAULT')


def fMotorModelSelect(No):
    switch = {0 : '0_DEFAULT', 
              1 : '1_DELTA',
              }

    return switch.get(No, '0_DEFAULT')

def fUnitSelect(No):
    switch = {0 : '0_STEP', 
              1 : '1_ANGLE',
              2 : '2_mm',
              3 : '3_Turns',
              }

    return switch.get(No, '0_STEP')

def fIsUseSelect(No):
    switch = {0 : '0_NonUse', 
              1 : '1_Use',
              }

    return switch.get(No, '0_NonUse')

# Display                0: English, 1: 繁體中文, 2:簡體中文, 3: 義大利文
ArrLanguage = { 
    "LANG_SET"      :["ENG"         ,"繁體"         ,"简体"         ,"Itali"],
    "N"             :[ "N"          ,"N"            ,"N"            ,"N"],
    "G"             :[ "G"          ,"G"            ,"G"            ,"G"],
    "X"             :[ "X-CAM"      ,"X-凸輪"       ,"X-凸轮"       ,"X-Cam"],
    "Y"             :[ "Y-FEED"     ,"Y-送料"       ,"Y-送料"       ,"Y-Feed"],
    "Z"             :[ "Z-ROTQ"     ,"Z-轉芯"       ,"Z-转芯"       ,"Z-ROTQ"],
    "A"             :[ "A"          ,"A-翻線"       ,"A-翻线"       ,"A"],
    "B"             :[ "B"          ,"B-捲線"       ,"B-卷线"       ,"B"],
    "C"             :[ "C"          ,"C-軸"         ,"C-轴"         ,"C"],
    "D"             :[ "D"          ,"D-軸"         ,"D-轴"         ,"D"],
    "E"             :[ "E"          ,"E-軸"         ,"E-轴"         ,"E"],
    "SPD"           :[ "SPD"        ,"SPD"          ,"SPD"          ,"SPD"],
    "T"             :[ "T"          ,"T"            ,"T"            ,"T"],
    "_PAUSE"        :["-PAUSE-"     ,"-暫停-"       ,"-暂停-"       ,"-PAUSE-"],
    "_OFF"          :["-OFF-"       ,"-關閉-"       ,"-关闭-"       ,"-OFF-"],
    "OFF"           :["OFF"         ,"關閉"         ,"关闭"         ,"OFF"],
    "AIR"           :["AIR"         ,"汽缸"         ,"汽缸"         ,"Cilindro"],
    "TH1"           :["TH1"         ,"探針1"        ,"探针1"        ,"Probe1"],
    "TH2"           :["TH2"         ,"探針2"        ,"探针2"        ,"Probe2"],
    "MODE"          :["MODE"        ," 模式"        ," 模式"        ,"MODE"],
    "MISSCNT"       :["MISS CNT"    ,"目前失誤量"   ,"目前失误量"   ,"MISS CNT"],
    "SETMISS"       :["SET MISS"    ,"設定失誤量"   ,"设定失误量"   ,"SET MISS"],
    "RATE"          :["RATE"        ,"生產速率"     ,"生产速率"     ,"RATE"],
    "QTYCNT"        :["QTY CNT"     ,"目前生產量"   ,"目前生产量"   ,"QTY CNT"],
    "SETQTY"        :["SET QTY"     ,"設定生產量"   ,"设定生产量"   ,"SET QTY"],
    "FILENO"        :["File No."     ,"檔案編號"     ,"档案编号"     ,"File No."],
    "AXIS"          :["Axis"        ,"軸"           ,"轴"           ,"Axis"],
    "AXISMode"      :["AXIS"        ,"刀具"         ,"刀具"         ,"AXIS"],
    "POS"           :["POS"         ,"位置"         ,"位置"         ,"POS"],
    "MAN"           :["MAN"         ,"手動"         ,"手动"         ,"MAN"],
    "MPG"           :["MPG"         ,"手輪"         ,"手轮"         ,"MPG"],
    "EDIT"          :["EDIT"        ,"編輯 "        ,"编辑 "        ,"EDIT"],
    "WORK"          :["WORK"        ,"生產 "        ,"生产 "        ,"WORK"],
    "TEST"          :["TEST"        ,"測試 "        ,"测试 "        ,"TEST"],
    "STEP"          :["STEP"        ,"單步 "        ,"单步 "        ,"STEP"],
    "MODY"          :["MODY"        ,"修改 "        ,"修改 "        ,"MODY"],
    "PARA"          :["PARA"        ,"參數 "        ,"参数 "        ,"PARA"],
    "HELP"          :["HELP"        ,"說明 "        ,"说明 "        ,"HELP"],
    "FileSave"      :["FILE SAVE"   ,"存檔 "        ,"存档"         ,"FILE SAVE"],
    "FileOpen"      :["FILE No"     ,"開檔 "        ,"开档"         ,"FILE No"],
    "0_OFF"         :["0-OFF"       ,"0-關閉"       ,"0-关闭"       ,"0-OFF"],
    "1_ON"          :["1-ON"        ,"1-開啟"       ,"1-开启"       ,"0-ON"],
    "0_DIR"         :["0-DIRECT"    ,"0-直接"       ,"0-直接"       ,"0-DIRECT"],
    "1_INDIR"       :["1-IN-DIR"    ,"1-間接"       ,"1-间接"       ,"1-INDIR"],   
    "2_IMMED"       :["2-Immed"     ,"2-立即"       ,"2-立即"       ,"2-Immed"],
    "3_TurnWire"    :["3-Turn"      ,"3-轉線"       ,"3-转线"       ,"3-Turn"],   
    "0_NonUse"      :["0-NonUse"    ,"0-不使用"     ,"0-不使用"     ,"0-NonUse"],
    "1_Use"         :["1-Use"       ,"1-使用"       ,"1-使用"       ,"1-Use"],
    "CYCLE"         :["cyc."        ,"週期"         ,"1-周期"       ,"cyc."],     
    "0_DEFAULT"     :["0-DEFAULT"   ,"0-預設"       ,"0-预设"       ,"0-DEFAULT"], 
    "1_DELTA"       :["1-DELTA"     ,"1-台達"       ,"1-台达"       ,"1-DELTA"], 
    "1_4000"        :["1-4000"      ,"1-4000型"     ,"1-4000型"     ,"1-4000"],    
    "1_USER"        :["1-USER"      ,"1-自定義"     ,"1-自定义"     ,"1-USER"],     
    "0_UltraSPD"    :["1-Ultra"     ,"0-超速率"     ,"0-超速率"     ,"0-Ultra"],     
    "1_AVDSPD"      :["1-AVG"       ,"1-均速率"     ,"1-均速率"     ,"1-AVG"],     
    "2_SelfSPD"     :["2-Self"      ,"2-自"         ,"2-自"        ,"2-Self"],  
    "Cam"           :["Cam"         ,"凸輪"         ,"凸轮"         ,"Cam"],
    "Feeding"       :["Feeding"     ,"送料"         ,"送料"         ,"Feeding"],
    "Rotating"      :["Rotating"    ,"轉芯"         ,"转芯"         ,"Rotating"],
    "Turning"       :["Turning"     ,"翻線"         ,"翻线"         ,"Turning"],
    "Reeling"       :["Reeling"     ,"捲取"         ,"卷取"         ,"Reeling"],
    "Cutter"        :["Cutter"      ,"切刀"         ,"切刀"         ,"Cutter"],
    "Clamping"      :["Clamping"    ,"夾耳"         ,"夹耳"         ,"Clamping"],
    "Sliding"       :["Sliding"     ,"滑座"         ,"滑座"         ,"Sliding"],
    "Scobing"       :["Scobing"     ,"翻線"         ,"翻线"         ,"Scobing"],
    "Folding"       :["Fold"        ,"折角"         ,"折角"         ,"Fold"]	,
    "Trans"         :["Shift"       ,"平移"         ,"平移"         ,"Shift"],
    "0_STEP"        :["0-SETP"      ,"0-格數"       ,"0-格数"       ,"0-SETP"],
    "1_ANGLE"       :["1-ANGLE"     ,"1-角度"       ,"1-角度"       ,"1-ANGLE"],
    "2_mm"          :["2-mm"        ,"2-mm"         ,"2-mm"         ,"2-mm"],
    "3_Turns"       :["3-Turns"     ,"3-圈數"       ,"3-圈数"        ,"3-Turns"],
    "SEC"           :["Sec"         ,"秒"           ,"秒"           ,"Sec"  ],
    "MIN"           :["Min"         ,"分鐘"         ,"分钟"         ,"Min"  ],
    "SPEED"         :["Speed"       ,"速度"         ,"速度"         ,"Speed"],
    "RATE"          :["Rate"        ,"速率"         ,"速率"         ,"Rate"],
    "0_Low"         :["0-Low"       ,"0-Low"        ,"0-Low"        ,"0-Low"],
    "1_High"        :["1-High"      ,"1-High"       ,"1-High"       ,"1-High"],
    "2_NoRef"       :["2-No Ref"    ,"2-不參考"     ,"2-不参考"     ,"2-No Ref"],
    "DEG"           :["(Deg)"       ,"(角度)"       ,"(角度)"       ,"(Deg)"],
   
    # PARA Pububuttom
    "MotorNo"       :["MOTOR NO"    ,"馬達編號"     ,"马达编号"     ,"MOTOR NO"    ],
    "MotorName"     :["MOT NAME"    ,"馬達名稱"     ,"马达名称"     ,"MOT NAME"    ],
    "MotorStep"     :["MOT GRID"    ,"馬達格數"     ,"马达格数"     ,"MOT GRID"    ],
    "MotorType"     :["MOT TYPE"    ,"馬達型態"     ,"马达型态"     ,"MOT TYPE"    ],
    "MotorFunction" :["MOT FUNC"    ,"馬達功能"     ,"马达功能"     ,"MOT FUNC"    ],
    "ZRTOrder"      :["HOME SEQ"    ,"原點順序"     ,"原点顺序"     ,"HOME SEQ"    ],
    "ZRTMode"       :["ZRT MODE"    ,"原點模式"     ,"原点模式"     ,"ZRT MODE"    ],
    "ZRTNew"        :["ZRT SET"     ,"新設原點"     ,"新设原点"     ,"ZRT SET"     ],
    "ZRTMapping"    :["ZRT CORR"    ,"原點對應"     ,"原点对应"     ,"ZRT CORR"    ],
    "MaxLimit"      :["AXIS MAX"    ,"最大極限"     ,"最大极限"     ,"AXIS MAX"    ],
    "MinLimit"      :["AXIS MIN"    ,"最小極限"     ,"最小极限"     ,"AXIS MIN"    ],
    "FeedSignal"    :["MOT NEAR"    ,"回報信號"     ,"回报信号"     ,"MOT NEAR"    ],
    "Language"      :["Language"    ,"語言設定"     ,"语言设定"     ,"Language"    ],
    "Model"         :["TYPE NO."    ,"機器型號"     ,"机器型号"     ,"TYPE NO."    ],
    "Y_Encoder"     :["Y-Encode"    ,"Y-編碼器"     ,"Y-编码器"     ,"Y-Encode"    ],
    "SafeDoor"      :["SHIELD"      ,"安全門"       ,"安全门"       ,"SHIELD"      ],
    "SafeEquip"     :["SENSOR"      ,"安全裝置"     ,"安全装置"     ,"SENSOR"      ],
    "Alarm"         :["W.LIGHT"     ,"警示燈"       ,"警示灯"       ,"W.LIGHT"     ],
    "CutDist"       :["Cut Dist"    ,"切刀距離"     ,"切刀距离"     ,"Cut Dist"    ],
    "SpeedMode"     :["RateMode"    ,"速率模式"     ,"速率模式"     ,"RateMode"    ],
    "SPDMode"       :["SPD Mode"    ,"SPD 模式"     ,"SPD 模式"     ,"SPD Mode"    ],
    "ZRTPosition"   :["ZRT POS"     ,"原點位置"     ,"原点位置"     ,"ZRT POS"     ],
    "ZRTCNT"        :["ZRT CYE"     ,"原點圈數"     ,"原点圈数"     ,"ZRT CYE"     ],
    "Gear0"         :["GEAR 0"      ,"齒輪比 0"     ,"齿轮比 0"     ,"GEAR 0"      ],
    "Gear1"         :["GEAR 1"      ,"齒輪比 1"     ,"齿轮比 1"     ,"GEAR 1"      ],
    "Mumer"         :["ENCR0"       ,"分周分子"     ,"分周分子"     ,"ENCR0"       ],
    "Demon"         :["ENCR1"       ,"分周分母"     ,"分周分母"     ,"ENCR1"       ],
    "ABReverse"     :["A/B Dir"     ,"A/B 反向"     ,"A/B 反向"     ,"A/B Dir"     ],
    "ZRTSignal"     :["Sensor"      ,"原點信號"     ,"原点信号"     ,"Sensor"      ],
    "FixedCheck"    :["ChkToPos"    ,"定點檢查"     ,"定点检查"     ,"ChkToPos"    ],
    "T1DecDist"     :["T1DecDis"    ,"T1 減距離"    ,"T1 减距离"    ,"T1DecDis"    ],
    "T2DecDist"     :["T2DecDis"    ,"T2 減距離"    ,"T2 减距离"    ,"T2DecDis"    ],
    "T3DecDist"     :["T3DecDis"    ,"T3 減距離"    ,"T3 减距离"    ,"T3DecDis"    ],
    "T4DecDist"     :["T4DecDis"    ,"T4 減距離"    ,"T4 减距离"    ,"T4DecDis"    ],
    "GearSpeed"     :["HAND SPD"    ,"手輪速度"     ,"手轮速度"     ,"HAND SPD"    ],
    "WireDist"      :["Wire Gap"    ,"送線間距"     ,"送线间距"     ,"Wire Gap"    ],
    "LINE"          :["LINE"        ,"LINE"         ,"LINE"         ,"LINE"        ],
    "LOGO"          :["LOGO"        ,"LOGO"         ,"LOGO"         ,"LOGO"        ],
    "OneProdut"     :["ONE"         ,"單一生產"     ,"单一生产"     ,"ONE"         ],
    "LockProduct"   :["LOCK PWD"    ,"鎖生產量"     ,"锁生产量"     ,"LOCK PWD"    ],
    "CoreCalibrate" :["ROTQ MDY"    ,"轉蕊校正"     ,"转蕊校正"     ,"ROTQ MDY"    ],
    "WireCalibrate" :["SPIN MDY"    ,"卷取校正"     ,"卷取校正"     ,"SPIN MDY"    ],
    "LOT"           :["BATCH"       ,"批量"         ,"批量"         ,"BATCH"       ],
    "SimFAST"       :["SIM FAST"    ,"模擬 FAST"    ,"模拟 FAST"    ,"SIM FAST"    ],
    "XEncoder"      :["X-Encode"    ,"X-編碼器"     ,"X-编码器"     ,"X-Encode"    ],
    "MotorModel"    :["MOT NO"      ,"馬達型號"     ,"马达型号"     ,"MOT NO"      ],

    # File Table
    "CurrentFileNo" :["Current File No.", "目前檔案編號", "目前档案编号"     ,"Current File No."],
    "Modfied_Time"  :["Modified Time"   , "修改時間"    , "修改时间"     ,"Modified Time"],
    "FileComment"   :["File Comment"    , "檔案註解"    , "文件注释"     ,"File Comment" ],

    #Download
    "ID"            :["ID"          ,"ID"           ,"ID"           ,"ID"           ],
    "Version"       :["Version"     ,"版本"         ,"版本"         ,"Version"      ],
    "ChangeLog"     :["Change Log"  ,"註解"         ,"注解"         ,"Change Log"   ],

    "YTotal"        :["Total Y"     ,"總送線量"     ,"总送线量"      ,"Total Y"     ],

    #None Data
    "None"          :["None"        ,"未知"         ,"未知"         ,"None"     ],
}


# Error Message
ArrErrorMessage = { 
    "Error"          :[ "Error",
                        "錯誤",
                        "错误",
                        "Error"
                        ],
    "File_No_Found"  :[ "File No Found",
                        "文件未找到",
                        "文件未找到",
                        "File No Found"],
    "Connection_Fail":[ "Connection Fail",
                        "連線異常",
                        "连线异常",
                        "Connection Fail"],
    "AnyKeyExit"     :[ "Any Key Exit",
                        "任何鍵離開",
                        "任何键离开",
                        "Any Key Exit"],
    "G8_Error"      :[  "Loop Setting Error",
                        "迴圈設定值錯誤",
                        "循环设定值错误",
                        "Loop Setting Error"],
    "USB_NotFound"      :[  "USB Disk Not Exist",
                        "USB磁碟不存在",
                        "USB磁碟不存在",
                        "USB Disk Not Exist"],
    "PROG_ZOFF_ERR"     :["Above Z-Axis have a program,but been off",
                        "Z軸以上有輸入程式,卻被關閉\n請使用測試模式",
                        "Z轴以上有输入程式,却被关闭\n请使用测试模式",
                        "Above Z-Axis have a program,but been off"],
    "Not_found_G0"     :["Please enter G0",
                        "請輸入程式結束",
                        "请输入程式结束",
                        "Please enter G0"],
}

ArrErrorMessageBox = { 
        0x01:   ["Motor Wire drop",
                "軸 馬 達 線 掉 了 ",
                "轴 马 达 线 掉 了",
                "Motor Wire drop"],
        0x02:   ["Return to origin failed",
                "軸 回 原 點 失 敗",
                "轴 回 原 点 失 败",
                "Return to origin failed"],
        0x03:   ["Jam !",#滑座x
                "動 作 錯 誤 !",
                "动 作 错 误 !",
                "Jam !"],
        0x04:   ["Test OK !",#滑座x
                "測 試 正 常 !",
                "测 试 正 常 !",
                "Test OK !"],
        0x05:   [" Fail\n START/TEST/STEP----Continue produce\nRESET------Return To Edit Screen",#探針
                " 失 誤\n啟 動/測 試/單 步 鍵----繼 續 生 產\n重 置 鍵---------回 到 編 輯 畫 面",
                " 失 误\n启 动/测 试/单 步 键----继 续 生 产\n重 置 键---------回 到 编 辑 画 面",
                " Fail\n START/TEST/STEP----Continue produce\nRESET------Return To Edit Screen"],
        0x06:   ["Test OK !",#探針
                "測 試 正 常",
                "测 试 正 常",
                "Test OK !"],
        0x07:   [" Oil System Failure ",
                "供 油 系 統 錯 誤",
                "供 油 系 统 错 误",
                "PROBLEMA SISTEMA OLIO"],
        0x08:   [" Ext. Device Failure ",
                "線 架 設 備 錯 誤",
                "线 架 设 备 错 误",
                " PROBLEMA SISTEMA ESTERNO "],
        0x09:   [" External Encoder Error ...",
                "外 接 解 碼 器 錯 誤",
                "外 接 解 码 器 错 误",
                " External Encoder Error ..."],
        0x0a:   ["Servo Failure !",
                "伺 服 失 敗!",
                "伺 服 失 败!",
                "Servo Failure !"],
        0x0b:   ["Servo Cutter Failure !",
                "伺 服 切 刀 失 敗",
                "伺 服 切 刀 失 败",
                "Servo Cutter Failure !"],
        0x0c:   [" Over SLide Limit Failure !\n\n RESET------Return To Edit Screen",
                "超 過 伺 服 滑 座 極 限 失 敗 !\n\n 重 置 鍵---------回 到 編 輯 畫 面",
                "超 过 伺 服 滑 座 极 限 失 败 !\n\n 重 置 键---------回 到 编 辑 画 面",
                " Over SLide Limit Failure !\n\n RESET------Return To Edit Screen"],
        0x0d:   [" Over software Limit!",
                "超 過 軟 體 極 限!",
                "超 过 软 体 极 限!",
                " Over software Limit!"],
        0x0e:   ["Go Home ...",
                "回 原 點 中.....",
                "回 原 点 中.....",
                "TORNA HOME ... "],
        0x0f:   [" Door Error ",
                "安 全 門 錯 誤",
                "安 全 门 错 误",
                " Door Error "],
        0x10:   [" Go Virtual Home ... ",
                "移 到 虛 擬 原 點 中 ...",
                "移 到 虚 拟 原 点 中 ...",
                "TORNA Virtual HOME ... "],
        0x11:   ["Test Knob not at Zero ",
                "測 試 旋 鈕 沒 有 關 成 零",
                "测 试 旋 钮 没 有 关 成 零",
                "Test Knob not at Zero "],
        0x12:   ["MPG Is Not Detected!!!",
                "未 偵 測 到 手 輪",
                "未 侦 测 到 手 轮",
                "MPG Is Not Detected!!!"],
        0x13:   ["Reach Miss No !",
                "超 過 失 誤 量 !",
                "超 过 失 误 量 !",
                "Reach Miss No !"],
        0x14:   [" Reach QTY No !",
                "超 過 生 產 量 !",
                "超 过 生 产 量 !",
                " Reach QTY No !"],
        0x15:   ["Press -A or +A Make ROTW-Axis Go Home !",
                "按 -A 或 +A 導 引 翻 線 回 原 點!",
                "按 -A 或 +A 导 引 翻 线 回 原 点!",
                "Press -A or +A Make ROTW-Axis Go Home !"],
        0x16:   ["Automatic Go Home ....",
                "自 動 回 原 點 中.....",
                "自 动 回 原 点 中.....",
                "Automatic Go Home ...."],
        # 0x17:   ["USB Disk Not Exist",
        #         "USB磁碟不存在",
        #         "USB磁碟不存在",
        #         "USB Disk Not Exist"],
        0x17:   ["New Function\n*** Hook-axis is ON ***\n can auto execution",
                "新功能\n***夾耳已打開***\n具有自動執行功能",
                "新功能\n***夹耳已打开***\n具有自动执行功能",
                "New Function\n*** Hook-axis is ON ***\n can auto execution"],
        # 0x18:   ["Motor Wire drop",
        #         "軸馬達線掉了",
        #         "轴马达线掉了",
        #         "Motor Wire drop"],
        # 0x19:   ["Motor Wire drop",
        #         "軸馬達線掉了",
        #         "轴马达线掉了",
        #         "Motor Wire drop"],
        # 0x1a:   ["Motor Wire drop",
        #         "軸馬達線掉了",
        #         "轴马达线掉了",
        #         "Motor Wire drop"],
        # 0x1b:   ["Motor Wire drop",
        #         "軸馬達線掉了",
        #         "轴马达线掉了",
        #         "Motor Wire drop"],

}


# Display                0: English, 1: 繁體中文, 2:簡體中文, 3: 義大利文
ArrComment = {
    "MotorStep"     :[  "MOTOR STEP SETTING",   
                        "馬達格數設定",
                        "马达格数设定",
                        "MOTOR STEP SETTING"],
    "MotorType"     :[  "[Motor Type] Set according to the motor type, in most cases： 0-SANYO, 1-Yaskawa Motor.",
                        "[馬達型態] 依馬達廠牌設定，大部分情況：0-三洋、1-安川馬達。",
                        "[马达型态] 依马达厂牌，设定情况：0-三洋、1-安川马达。",
                        "[Motor Type] Set according to the motor type, in most cases: 0-SANYO, 1-Yaskawa Motor."],
    "MotorFunction" :[  "[Motor function] 0-Cam, 1-Feeding, 2-Rotating, 3-Turning, 4-Reeling, 5-Cutter, 6-Clamping, 7-Sliding, 8-Scobing (trimming, required Matching parameters), 9-Fold, 10-Shift.",
                        "[馬達功能] 0-凸輪、1-送料、2-轉芯、3-翻線、4-捲取、5-切刀、6-夾耳、7-滑座、8-翻線(修整，須配合參數)，9-折角，10-平移。",
                        "[马达功能] 0-凸轮、1-送料、2-转芯、3-翻线、4-卷取、5-切刀、6-夹耳、7-滑座、8-翻线(修整，须配合参数)，9-折角，10-平移。",
                        "[Motor function] 0-Cam, 1-Feeding, 2-Rotating, 3-Turning, 4-Reeling, 5-Cutter, 6-Clamping, 7-Sliding, 8-Scobing (trimming, required Matching parameters), 9-Fold, 10-Shift."],
    "ZRTOrder"      :[  "[Origin sequence] ",
                        "[原點順序] 執行回原點的運轉方向及先後順序，* 表示回原點， - 表示反向回原點；數字小的先回原點，數字一樣同時回原點。",
                        "[原点顺序] 执行回原点的运转方向及先后顺序，* 表示回原点， - 表示反向回原点；数字小的先回原点，数字一样同时回原点。",
                        "[Origin sequence] "],
    "ZRTMode"       :[  "[Origin Mode]",
                        "[原點模式] 0-直接、1-間接、2-立即、3-轉線；模式設定與馬達接線方式有關，詳細內容請參考說明檔。",
                        "[原点模式] 0-直接、1-间接、2-立即、3-转线；模式设定与马达接线方式有关，详细内容请参考说明档。",
                        "[Origin Mode]"],
    "ZRTNew"        :[  "[New Origin]",
                        "[新設原點] 回原點後再偏移的格數值，+/-表示偏移的方向。",
                        "[新设原点] 回原点后再偏移的格数值，+/-表示偏移的方向。",
                        "[New Origin]"],
    "ZRTMapping"    :[  "[Origin Mapping]",
                        "[原點對應] 適用於原點模式為 1-間接，2-立即：原點IO信號對應。",
                        "[原点对应] 适用于原点模式为 1-间接，2-立即：原点IO信号对应。",
                        "[Origin Mapping]"],
    "MaxLimit"      :[  "[Max Limit]",
                        "[最大極限] 各軸往正方向能移動的最大距離，編輯程式及手動時檢查。",
                        "[最大极限] 各轴往正方向能移动的最大距离，编辑程式及手动时检查。",
                        "[Max Limit]"],
    "MinLimit"      :[  "[Min Limit]",
                        "[最小極限] 各軸往正方向能移動的最大距離，編輯程式及手動時檢查。",
                        "[最小极限] 各轴往正方向能移动的最大距离，编辑程式及手动时检查。",
                        "[Min Limit]"],
    "FeedSignal"    :[  "[Signal Report ",
                        "[回報信號] 參數設定 0 時：馬達線未接會回報錯誤；設定 1 時：馬達線未接不會回到錯誤，詳細內容請參考說明檔。",
                        "[回报信号] 参数设定 0 时：马达线未接会回报错误；设定 1 时：马达线未接不会回到错误，详细内容请参考说明档。",
                        "[Signal Report "],
    "Language"      :[  "[Language]",
                        "[語言設定] 0-英文、1-繁體中文、2-簡體中文、3-義大利文。",
                        "[语言设定] 0-英文、1-繁体中文、2-简体中文、3-义大利文。",
                        "[Language]"],
    "Model"         :[  "[Machine model] Set according to the customer's machine model",
                        "[機器型號] 依客戶機器型號設定",
                        "[机器型号] 依客户机器型号设定",
                        "[Machine model] Set according to the customer's machine model"],
    "Y_Encoder"     :[  "[Y Encoder]",
                        "[Y編碼器]",
                        "[Y编码器]",
                        "[Y Encoder"],
    "SafeDoor"      :[  "[Safety door] When safety door is installed, the opening function can be selected; 0-Close, 1-Open",
                        "[安全門] 有加裝安全門時，可選擇開啟功能；0-關閉、1-開啟。",
                        "[安全门] 有加装安全门时，可选择开启功能；0-关闭、1-开启。",
                        "[Safety door] When safety door is installed, the opening function can be selected; 0-close, 1-open"],
    "SafeEquip"     :[  "[Safety Equipment]",
                        "[安全裝置]", 
                        "[安全装置]",
                        "[Safety Equipment]"],
    "Alarm"         :[  "[Alarm] When machine sends out an error message, turn off the output light as a warning; 0-, 1-on, IO point is (B2), only applicable to SW v3.52 and later versions",
                        "[警示燈] 機台發生錯誤訊息時，以黃燈閃爍作為警示；0-關閉、1-開啟，IO輸出點為(B2)，僅適用於軟體v3.52以後版本。",
                        "【提醒】机台发出错误消息时，以关闭输出灯作为警示；0-、1-开启，IO点为（B2），仅适用于软体v3.52以后版本。",
                        "[Alarm] When machine sends out an error message, turn off the output light as a warning; 0-, 1-on, IO point is (B2), only applicable to SW v3.52 and later versions"],
    "CutDist"       :[  "[Cutter distance]",
                        "[切刀距離] 伺服切刀固定來回的移動距離，最大值設限15,000格，修改此參數系統會自動將[切刀距離]填入切刀軸[最大極限]，當作軟體極限設定。",
                        "[切刀距离] 伺服切刀固定来回的移动距离，最大值设限15,000格，修改此参数系统会自动将[切刀距离]填入切刀轴[最大极限]，当作软体极限设定。",
                        "[Cutter distance] "],
    "SpeedMode"     :[  "[Speed Ratio Mode]",
                        "[速率模式] 0-超速率(盡量使X軸保持生產速率，其他軸可能超過生產速率)、1-均速率(各軸不超過生產速率)、2-自(自各軸生產速率)。",
                        "[速率模式] 0-超速率(尽量使X轴保持生产速率，其他轴可能超过生产速率)、1-均速率(各轴不超过生产速率)、2-自(自各轴生产速率)。",
                        "[Speed Ratio Mode]"],
    "SPDMode"       :[  "[SPD mode] 0-SPD can input 2 digits, 1-SPD can input 3 digits, the lowest digit represents the number after the decimal",
                        "[SPD 模式] 0-SPD可輸入2位數、1-SPD可輸入3位數，最低位代表小數點後的數字。",
                        "[SPD 模式] 0-SPD可输入2个、1-SPD可输入3个数字后，最低位代表小数的数字。",
                        "[SPD mode] 0-SPD can input 2 digits, 1-SPD can input 3 digits, the lowest digit represents the number after the decimal"],
    "ZRTPosition"   :[  "[Origin Position]",
                        "[原點位置] 由密碼輸入 5217，設定絕對值馬達原點位置。",
                        "[原点位置] 由密码输入 5217，设定绝对值马达原点位置。",
                        "[Origin Position]"],
    "ZRTCNT"        :[  "[Origin Coil Number]",
                        "[原點圈數] 由密碼輸入 5217，設定絕對值馬達原點位置。",
                        "[原点圈数] 由密码输入 5217，设定绝对值马达原点位置。",
                        "[Origin Coil Number]"],
    "Gear0"         :[  "[Gear Ratio 0]",
                        "[齒輪比0] 預設為1,000，絕對值馬達齒輪比。",
                        "[齿轮比0]预设为1000，绝对值马达比。",
                        "[Gear Ratio 0]"],
    "Gear1"         :[  "[Gear Ratio 1]",
                        "[齒輪比 1] 預設為1,000，絕對值馬達齒輪比。",
                        "[齿轮比 1]预设为1000，绝对值马达比。",
                        "[Gear Ratio 1]"],
    "Mumer"         :[  "[Division numerator] ",
                        "[分周分子] 預設為1,000，調整驅動器回授信號分周比。",
                        "[分周分子] 预设为1,000，调整驱动器回授信号分周比。",
                        "[Division numerator]"],
    "Demon"         :[  "[Division denominator] ",
                        "[分周分母] 預設為1,000，調整驅動器回授信號分周比。",
                        "[分周分子] 预设为1,000，调整驱动器回授信号分周比。",
                        "[Division denominator]"],
    "ABReverse"     :[  "[A/B Reverse]",
                        "[A/B 反向] 設定驅動器回授信號是否反向；0-不反向、1-反向。",
                        "[A/B 反向] 设置驱动器回授信号是否反向；0-不反向、1-反向。",
                        "[A/B Reverse]"],
    "ZRTSignal"     :[  "[Origin signal]",
                        "[原點信號] 預設為 1- High，馬達無安裝 Sensor或有外接Encoder時，若[原點模式]為 0-直接，[原點信號]需視情況調整，(與驅動器設定相關)[New] 2-不參考。",
                        "[原点信号] 预设为 1- High，马达无安装 Sensor或有外接Encoder时，若[原点模式]为 0-直接，[原点信号]需视情况调整，(与驱动器设定相关)[New] 2-不参考。",
                        "[Origin signal]"],
    "FixedCheck"    :[  "[Position check]",
                        "[定位檢查] 使用到定位功能時（常用參數[到定位]設定 1，或是程式有壓紅字），設定幾個週期時間檢查一次（一個週期=100us），視各軸馬達情況調整。",
                        "[定位检查] 使用到定位功能时（常用参数[到定位]设置 1，或是程序有压红字），设置几个周期时间检查一次（一个周期=100us），视各轴马达情况调整。",
                        "[Position check]"],
    "T1DecDist"     :[  "[T1 Distance Reduction]",
                        "[T1 減距離]",
                        "[T1 减距离]",
                        "[T1 Distance Reduction]"],
    "T2DecDist"     :[  "[T2 Distance Reduction]",
                        "[T2 減距離]",
                        "[T2 减距离]",
                        "[T2 Distance Reduction]"],
    "T3DecDist"     :[  "[T3 Distance Reduction]",
                        "[T3 減距離]",
                        "[T3 减距离]",
                        "[T3 Distance Reduction]"],
    "T4DecDist"     :[  "[T4 Distance Reduction]",
                        "[T4 減距離]",
                        "[T4 减距离]",
                        "[T4 Distance Reduction]"],
    "GearSpeed"     :[   "[Handwheel Speed]",
                        "[手輪速度]",
                        "[手轮速度]",
                        "[Handwheel Speed]"],
    "WireDist"      :[  "[Feeding gap]",
                        "[送線間隙]",
                        "[送线间隙]",
                        "[Feeding gap]"],
    "LINE"          :[  "[LINE]",
                        "[LINE]",
                        "[LINE]",
                        "[LINE]"],
    "LOGO"          :[  "[LOGO]",
                        "[LOGO]",
                        "[LOGO]",
                        "[LOGO]"],
    "OneProdut"     :[  "[Production Lot]", 
                        "[單一生產]",
                        "[单一生产]",
                        "[Production Lot]"],
    "LockProduct"   :[  "[Production Lock]",
                        "[鎖生產量]",
                        "[锁生产量]",
                        "[Production Lock]"],
    "CoreCalibrate" :[  "[Core Calibration]",
                        "[轉芯校正]",
                        "[转芯校正]",
                        "[Core Calibration]"],
    "WireCalibrate" :[  "[Rewinder Calibration]",
                        "[捲取校正]",
                        "[卷取校正]",
                        "[Rewinder Calibration]"],
    "LOT"           :[  "[LOT]",
                        "[批量]",
                        "[批量]",
                        "[LOT]"], 
    "SimFAST"       :[  "[Fast Simulation]",
                        "[模擬FAST]"
                        "[模拟FAST]"
                        "[Fast Simulation]"],
    "XEncoder"      :[  "[X Encoder]",
                        "[X 編碼器]",
                        "[X 编码器]",
                        "[X Encoder]"],
    "MotorModel"    :[  "[Motor Type]",
                        "[馬達型號]",
                        "[马达型号]",
                        "[Motro Type]"],
    "BoxT"          :[  "[Inch Move T]",
                        "[寸動 T]",
                        "[寸动 T]",
                        "[Inch Move T]"],
    "ProbeDelay"    :[  "[Probe Delay]",
                        "[探針延遲]",
                        "[探针延迟]",
                        "[Probe Delay]"],
    #PARA_SIM Comment
    "Unit"          :[  "[Unit]",
                        "[單位]",
                        "[单位]",
                        "[Unit]"],
    "MotorSpeed"    :[  "[Motor Speed]",
                        "[馬達速度]",
                        "[马达速度]",
                        "[Motor Speed]"],
    "PNSpeed"       :[  "[ACC and DeACC]",
                        "[加减速]",
                        "[加减速]",
                        "[ACC and DeACC]"],
    "ZeroSpeed"     :[  "[Zero Speed]",
                        "[歸零速度]",
                        "[归零速度]",
                        "[Zero Speed]"],
    "Delay"         :[  "[Delay]",
                        "[延遲]",
                        "[延迟]",
                        "[Delay]"],
    "ToPos"         :[  "[Go Position]",
                        "[到定位]",
                        "[到定位]",
                        "[Go Position]"],
    "ZeroGo"        :[  "[Zero Pre-Go]",
                        "[歸零預走]",
                        "[归零预走]",
                        "[[Zero Pre-Go]"],
    "UnitExchange"  :[  "[Unit-Conversion]",
                        "[單位換算]",
                        "[单位换算]",
                        "[Unit-Conversion]"],
    "SelfSpeed"     :[  "[Self-Rate]",
                        "[自速率]",
                        "[自速率]",
                        "[Self-Rate]"],
    "BIOSReset"     :[  "[BIOS Reset]",
                        "[BIOS重置]",
                        "[BIOS重置]",
                        "[BIOS Reset]"],
    "ScreenProt"    :[  "[Screen Saver]",
                        "[螢幕保護]",
                        "[萤幕保护]",
                        "[Screen Saver]"],
    "AutoPower"     :[  "[Auto Power Off]",
                        "[自動關電]",
                        "[自动关电]",
                        "[Auto Power Off]"],
    "FoldAngle"     :[  "[Flod Angle]",
                        "[翻線角度]",
                        "[翻线角度]",
                        "Flod Angle]"],
    "WireAcc"       :[  "[Wire Frame ACC]",
                        "[線架加速]",
                        "[线架加速]",
                        "[Wire Frame ACC]"],
    "USBDisk"       :[  "[USB Disk]",
                        "[USB磁碟]",
                        "[USB磁碟]",
                        "[USB Disk]"],
    "SlideLimit"    :[  "[Slide Limit]",
                        "[滑座極限]",
                        "[滑座极限]",
                        "[Slide Limit]"],
    "CylinderRel"   :[  "[Cylinder Release]",
                        "[汽缸解除]",
                        "[汽缸解除]",
                        "[Cylinder Release]"],
    "WireReset"     :[  "[Rewind To Zero]",
                        "[捲取歸零]",
                        "[卷取归零]",
                        "[Rewind To Zero]"],
    "ManX100"       :[  "[Handwheel X100]",
                        "[手輪X100]",
                        "[手轮X100]",
                        "[Handwheel X100]"],
    "WirePause"     :[  "[Feeding Pause]",
                        "[送線暫停]",
                        "[送线暂停]",
                        "[Feeding Pause]"],
    "WireTime"       :[ "[Wire Time]",
                        "[線架時間]",
                        "[线架時間]",
                        "[Wire Time]"],
    "WireMode"      :[  "[Wire Frame Mode]",
                        "[線架模式]",
                        "[线架模式]",
                        "[Wire Frame Mode]"],
    "WorkMode"      :[  "[Work Mode]",
                        "[工作模式] 0-速度、1-速率",
                        "[工作模式] 0-速度、1-速率",
                        "[Work Mode]"],
    "PNAccSW"       :[  "[ACC and DeACC]",
                        "[加減速] 0-使用、1-不使用",
                        "[加減速] 0-使用、1-不使用",
                        "[ACC and DeACC]"],
    "ProbeTime"     :[  "[Probe Time]",
                        "[探針時間]",
                        "[探针时间]",
                        "[Probe Time]"],
    "ProdPWD"       :[  "[Production Password]",
                        "[生產密碼]",
                        "[生产密码]",
                        "[Production Password]"],
    "ProdDelay"     :[  "[Production Delay]",
                        "[生產延遲] 0-使用、1-不使用",
                        "[生产延迟] 0-使用、1-不使用",
                        "[Production Delay]"],
    "XReverse"      :[  "[X-axis Reverse]",
                        "[X軸反向] 0-使用、1-不使用",
                        "[X轴反向] 0-使用、1-不使用",
                        "[X-axis Reverse]"],
    "KeyLock"       :[  "[Keyboard Lock]",
                        "[鍵盤鎖住] 0-使用、1-不使用",
                        "[键盘锁住] 0-使用、1-不使用",
                        "[Keyboard Lock]"],
    "CheckOff"      :[  "[Oil Check Lifted]",
                        "[油檢解除] 0-關閉、1-開啟",
                        "[油检解除] 0-关闭、1-开启",
                        "[Oil Check Lifted]"],
}
