s="      this is string example0000....wow!!!     "
print("len=",len(s),"s=",s)
print("test strip().......")
s1=s.strip()
print("len=",len(s1),"s1=",s1)
s2=s.strip('0')
print("len=",len(s2),"s2=",s2)
s3=s.strip('!')
print("len=",len(s3),"s3=",s3)
s4=s1.strip('!')
print("len=",len(s4),"s4=",s4)

print("test lstrip().........")
s1=s.lstrip()
print("len=",len(s1),"s1=",s1)
s2=s.lstrip('0')
print("len=",len(s2),"s2=",s2)
s3=s.lstrip('!')
print("len=",len(s3),"s3=",s3)
s4=s1.lstrip('!')
print("len=",len(s4),"s4=",s4)

print("test rstrip().........")
s1=s.rstrip()
print("len=",len(s1),"s1=",s1)
s2=s.rstrip('0')
print("len=",len(s2),"s2=",s2)
s3=s.rstrip('!')
print("len=",len(s3),"s3=",s3)
s4=s1.rstrip('!')
print("len=",len(s4),"s4=",s4)
